# Generated by Django 3.2.7 on 2022-09-05 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuotationID', models.CharField(blank=True, max_length=5)),
                ('BillToBuilding', models.CharField(blank=True, max_length=100)),
                ('ShipToState', models.CharField(blank=True, max_length=100)),
                ('BillToCity', models.CharField(blank=True, max_length=100)),
                ('ShipToCountry', models.CharField(blank=True, max_length=100)),
                ('BillToZipCode', models.CharField(blank=True, max_length=100)),
                ('ShipToStreet', models.CharField(blank=True, max_length=100)),
                ('BillToState', models.CharField(blank=True, max_length=100)),
                ('ShipToZipCode', models.CharField(blank=True, max_length=100)),
                ('BillToStreet', models.CharField(blank=True, max_length=100)),
                ('ShipToBuilding', models.CharField(blank=True, max_length=100)),
                ('ShipToCity', models.CharField(blank=True, max_length=100)),
                ('BillToCountry', models.CharField(blank=True, max_length=100)),
                ('U_SCOUNTRY', models.CharField(blank=True, max_length=100)),
                ('U_SSTATE', models.CharField(blank=True, max_length=100)),
                ('U_SHPTYPB', models.CharField(blank=True, max_length=100)),
                ('U_BSTATE', models.CharField(blank=True, max_length=100)),
                ('U_BCOUNTRY', models.CharField(blank=True, max_length=100)),
                ('U_SHPTYPS', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AppSlave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Min', models.FloatField(default=0)),
                ('Max', models.FloatField(default=0)),
                ('Level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineNum', models.IntegerField(default=0)),
                ('QuotationID', models.CharField(blank=True, max_length=5)),
                ('Quantity', models.IntegerField(default=0)),
                ('UnitPrice', models.FloatField(default=0)),
                ('DiscountPercent', models.FloatField(default=0)),
                ('ItemCode', models.CharField(blank=True, max_length=20)),
                ('ItemDescription', models.CharField(blank=True, max_length=150)),
                ('TaxCode', models.CharField(blank=True, max_length=10)),
                ('U_FGITEM', models.CharField(blank=True, max_length=20)),
                ('CostingCode2', models.CharField(blank=True, max_length=20)),
                ('ProjectCode', models.CharField(blank=True, max_length=20)),
                ('FreeText', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaxDate', models.CharField(blank=True, max_length=30)),
                ('DocDueDate', models.CharField(blank=True, max_length=30)),
                ('ContactPersonCode', models.CharField(blank=True, max_length=5)),
                ('DiscountPercent', models.FloatField(blank=True, max_length=5)),
                ('DocDate', models.CharField(blank=True, max_length=30)),
                ('CardCode', models.CharField(blank=True, max_length=30)),
                ('Comments', models.CharField(blank=True, max_length=150)),
                ('SalesPersonCode', models.CharField(blank=True, max_length=5)),
                ('DocumentStatus', models.CharField(blank=True, max_length=50)),
                ('CancelStatus', models.CharField(blank=True, max_length=50)),
                ('DocCurrency', models.CharField(blank=True, max_length=50)),
                ('DocTotal', models.CharField(blank=True, max_length=50)),
                ('CardName', models.CharField(blank=True, max_length=150)),
                ('VatSum', models.CharField(blank=True, max_length=50)),
                ('CreationDate', models.CharField(blank=True, max_length=50)),
                ('DocEntry', models.CharField(blank=True, max_length=5)),
                ('PaymentGroupCode', models.CharField(blank=True, max_length=5)),
                ('U_QUOTNM', models.CharField(blank=True, max_length=100)),
                ('U_PREQUOTATION', models.CharField(blank=True, max_length=100)),
                ('U_PREQTNM', models.CharField(blank=True, max_length=250)),
                ('U_LEADID', models.IntegerField(default=0)),
                ('U_LEADNM', models.CharField(blank=True, max_length=150)),
                ('U_Term_Condition', models.TextField(blank=True)),
                ('U_TermInterestRate', models.FloatField(default=0)),
                ('U_TermPaymentTerm', models.CharField(blank=True, max_length=100)),
                ('U_TermDueDate', models.CharField(blank=True, max_length=100)),
                ('BPLID', models.CharField(blank=True, max_length=5)),
                ('U_OPPID', models.CharField(blank=True, max_length=5)),
                ('U_OPPRNM', models.CharField(blank=True, max_length=100)),
                ('U_FAV', models.CharField(blank=True, max_length=10)),
                ('U_APPROVENM', models.CharField(blank=True, max_length=30)),
                ('Level1Status', models.CharField(blank=True, max_length=30)),
                ('Level2Status', models.CharField(blank=True, max_length=30)),
                ('Level3Status', models.CharField(blank=True, max_length=30)),
                ('FinalStatus', models.CharField(blank=True, max_length=30)),
                ('CreateDate', models.CharField(blank=True, max_length=30)),
                ('CreateTime', models.CharField(blank=True, max_length=30)),
                ('UpdateDate', models.CharField(blank=True, max_length=30)),
                ('UpdateTime', models.CharField(blank=True, max_length=30)),
                ('APPROVEID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='APPROVEID', to='Employee.employee', to_field='SalesEmployeeCode')),
                ('Level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Level1', to='Employee.employee', to_field='SalesEmployeeCode')),
                ('Level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Level2', to='Employee.employee', to_field='SalesEmployeeCode')),
                ('Level3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Level3', to='Employee.employee', to_field='SalesEmployeeCode')),
            ],
        ),
    ]
