# Generated by Django 3.2.13 on 2022-09-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='Attach',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quotation',
            name='DelTerm',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='Discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='GST',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quotation',
            name='Intall',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='Project',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='QuotType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='Subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
