# Generated by Django 3.2.13 on 2022-09-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0002_auto_20220906_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='QTNO',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
