# Generated by Django 3.2.13 on 2022-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0003_quotation_qtno'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressextension',
            name='BillToRemark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='ShipToRemark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ApprvReq',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='LOCharges',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='MICharges',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='OthInstruct',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='QuotStat',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
