# Generated by Django 3.2.13 on 2022-10-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0004_auto_20220929_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='Tax',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='UomNo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
