# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0009_auto_20230502_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuotationID', models.CharField(blank=True, max_length=5)),
                ('File', models.CharField(blank=True, max_length=255)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotStatusRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuotationID', models.CharField(blank=True, max_length=5)),
                ('SalesEmployeeCode', models.CharField(blank=True, max_length=5)),
                ('Status', models.CharField(blank=True, max_length=50)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='documentlines',
            name='EndDate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Frequency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='IsService',
            field=models.CharField(default='tNO', max_length=10),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='ReferenceItem',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='ReferenceSerial',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='StartDate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='TaxRate',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='CreatedBy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='DepName',
            field=models.CharField(blank=True, default='New Product', max_length=150),
        ),
        migrations.AddField(
            model_name='quotation',
            name='PRID',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='PoAmt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='PoDate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='PoNo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ShippingAndHandling',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='TermsAndConditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='U_Pay1',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='U_Pay2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='U_Pay3',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='U_Pay4',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='U_Pay5',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
