# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=500)),
                ('CreatedBy', models.CharField(max_length=50)),
                ('CreatedDate', models.CharField(max_length=50)),
                ('CreatedTime', models.CharField(max_length=50)),
                ('Data', models.TextField(max_length=10000)),
            ],
        ),
    ]
