# Generated by Django 3.2.13 on 2023-01-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industries',
            name='IndustryName',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
