from django.urls import path,include
from .views import *

urlpatterns = [
    path('create', create),
    path('all', all),
    path('all_filter', all_filter),
    path('all_filter_multi', all_filter_multi),    
    path('all_filter_assignto', all_filter_assignto),
    path('all_filter_reportingto', all_filter_reportingto),
    path('reportingto_upper', reportingto_upper),
    path('reportingto_lower', reportingto_lower),
    path('reportingto_lower_all', reportingto_lower_all),
    path('get_help', get_help),
    path('department', department),
    path('subdepartment', subdepartment),
    path('subdepartment_filter', subdepartment_filter),
    path('subdepartment_filter_multi', subdepartment_filter_multi),
    path('role', role),
    path('role_filter', role_filter),
    path('role_filter_multi', role_filter_multi),
    path('dashboard', dashboard),
    path('opportunity_bystage', opportunity_bystage),
    path('movingitems', movingitems),
    path('movingitems_count', movingitems_count),
    path('invoice_counter', invoice_counter),
    path('target_create', target_create),
    path('target_all', target_all),
    path('employee_target_sell', employee_target_sell),
    path('target_anu_ach', target_anu_ach),
    path('targetqtm_create', targetqtm_create),
    path('targetyr_create', targetyr_create),
    path('targetqty_close', targetqty_close),
    path('targetyr_close', targetyr_close),
    path('targetqtm_all', targetqtm_all),
    path('targetyr_all', targetyr_all),
    path('targetyr_all_filter', targetyr_all_filter),    
    path('analytics', analytics),
    path('top5bp', top5bp),
    path('top5itembyamount', top5itembyamount),
    path('one',one),
    path('login',login),
    path('update', update),
    path('delete', delete),
    path('prod_lead', ProductLead),
    path('proj_lead', ProjectLead),
    path('sync', sync),
    path('logout',logout),
    path('login_support',login_support),
    
    path('service_employee_list',service_employee_list),

]
