# Generated by Django 3.2.7 on 2022-09-05 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FactorCode', models.CharField(max_length=50)),
                ('FactorDescription', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.FloatField(default=0)),
                ('Name', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitPrice', models.FloatField(default=0)),
                ('Currency', models.CharField(default='INR', max_length=50)),
                ('DiscountPercent', models.FloatField(default=0)),
                ('ItemCode', models.CharField(blank=True, max_length=50)),
                ('ItemName', models.CharField(blank=True, max_length=150)),
                ('TaxCode', models.CharField(blank=True, max_length=50)),
                ('U_DIV', models.CharField(blank=True, max_length=10)),
                ('InStock', models.IntegerField(default=0)),
                ('ItemsGroupCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category', to_field='Number')),
            ],
        ),
    ]
