# Generated by Django 3.2.13 on 2023-08-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_item_uomno'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='At_Capacity',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='Ct_Capacity',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='Ht_Capacity',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='Machine_Body_Material',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='Machine_Colour',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='Machine_Dimension',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='Pro_Capacity',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='Special_Remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Tap_Qty',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='Tap_Type',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='Type_of_Machine',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
