# Generated by Django 3.2.13 on 2023-08-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Item', '0003_auto_20230822_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrderStatusRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=5)),
                ('SalesEmployeeCode', models.CharField(blank=True, max_length=5)),
                ('Status', models.CharField(blank=True, max_length=50)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='approval_status',
            field=models.CharField(blank=True, default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='approved_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemsGroupCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Category.category', to_field='Number'),
        ),
    ]
