# Generated by Django 3.2.13 on 2023-09-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0004_auto_20230822_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=0, unique=True)),
                ('GroupName', models.CharField(max_length=100)),
            ],
        ),
    ]
