# Generated by Django 3.2.13 on 2023-09-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0006_item_itemsgroupmastercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ItemsGroupMasterCode',
        ),
    ]
