# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0008_item_itemsgroupmastercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='IsService',
            field=models.CharField(default='tNo', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='ManageSerialNumbers',
            field=models.CharField(default='tNO', max_length=10),
        ),
    ]
