import os
os.system("python manage.py makemigrations Activity")
os.system("python manage.py makemigrations Branch")
os.system("python manage.py makemigrations BusinessPartner")
os.system("python manage.py makemigrations Campaign")
os.system("python manage.py makemigrations Category")
os.system("python manage.py makemigrations Company")
os.system("python manage.py makemigrations Countries")
os.system("python manage.py makemigrations Employee")
os.system("python manage.py makemigrations Industries")
os.system("python manage.py makemigrations Invoice")
os.system("python manage.py makemigrations Item")
os.system("python manage.py makemigrations Lead")
os.system("python manage.py makemigrations Notification")
os.system("python manage.py makemigrations Opportunity")
os.system("python manage.py makemigrations Order")
os.system("python manage.py makemigrations PaymentTermsTypes")
os.system("python manage.py makemigrations Project")
os.system("python manage.py makemigrations Quotation")
os.system("python manage.py makemigrations Tender")
#os.system("python manage.py migrate")
os.system("pause")

