# Generated by Django 3.2.13 on 2022-11-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.CharField(blank=True, max_length=50)),
                ('TransactId', models.CharField(blank=True, max_length=50)),
                ('TotalAmt', models.CharField(blank=True, max_length=20)),
                ('TransactMod', models.CharField(blank=True, max_length=50)),
                ('DueAmount', models.CharField(blank=True, max_length=50)),
                ('PaymentDate', models.CharField(blank=True, max_length=50)),
                ('ReceivedAmount', models.CharField(blank=True, max_length=50)),
                ('Remarks', models.TextField(blank=True)),
                ('createDate', models.CharField(blank=True, max_length=100)),
                ('createTime', models.CharField(blank=True, max_length=100)),
                ('createdBy', models.IntegerField(default=0)),
                ('updateDate', models.CharField(blank=True, max_length=100)),
                ('updateTime', models.CharField(blank=True, max_length=100)),
                ('updatedBy', models.IntegerField(default=0)),
                ('CardCode', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
