# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remark', models.TextField(blank=True, max_length=2000)),
                ('SourceType', models.CharField(blank=True, max_length=50)),
                ('Type', models.CharField(blank=True, choices=[('1', 'Poor'), ('2', 'Average'), ('3', 'Good'), ('4', 'Excelent')], default='Good', max_length=50)),
                ('Rating', models.CharField(blank=True, max_length=50)),
                ('SourceID', models.CharField(blank=True, max_length=10)),
                ('CardCode', models.CharField(blank=True, max_length=20)),
                ('CreatedDate', models.CharField(blank=True, max_length=20)),
                ('CreatedTime', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
