# Generated by Django 4.2.2 on 2023-09-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_department_subdepartment_employee_countrycode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='subdep',
        ),
    ]
