# Generated by Django 4.2.2 on 2023-09-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_remove_employee_dep_remove_employee_subdep'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subdep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.subdepartment'),
        ),
    ]
