# Generated by Django 3.2.13 on 2022-09-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpbranch',
            name='BranchType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bpbranch',
            name='LandLine',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
