# Generated by Django 3.2.13 on 2022-09-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0002_auto_20220905_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='bpsource',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='country_code',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='intProdCat',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='intProjCat',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='source_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='state',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='state_code',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='zone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
