# Generated by Django 3.2.13 on 2022-09-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0003_auto_20220927_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='country',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='state',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='state_code',
        ),
    ]
