# Generated by Django 3.2.13 on 2022-09-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0004_auto_20220928_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpaddresses',
            name='BillToRemark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bpbranch',
            name='ShipToRemark',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
