# Generated by Django 3.2.13 on 2022-10-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0005_auto_20220929_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='CustomerStatus',
            field=models.CharField(default='Prospect', max_length=100),
        ),
    ]
