# Generated by Django 3.2.13 on 2022-10-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0006_businesspartner_customerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpemployee',
            name='Alternateno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='CreatedBy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
