# Generated by Django 3.2.13 on 2022-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0008_auto_20221010_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_prefix', models.CharField(blank=True, max_length=100)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerGroup', models.CharField(blank=True, max_length=100)),
                ('Code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerZone', models.CharField(blank=True, max_length=100)),
                ('Code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='BPCustCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='intProdCat',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='intProjCat',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
