# Generated by Django 3.2.13 on 2022-11-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0009_auto_20221011_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='U_Landline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
