# Generated by Django 3.2.13 on 2023-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0012_alter_bpaddresses_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpemployee',
            name='Address',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
