# Generated by Django 3.2.13 on 2023-05-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0013_alter_bpemployee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpbranch',
            name='BuildingFloorRoom',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bpbranch',
            name='ShipToRemark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bpbranch',
            name='Street',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bpemployee',
            name='Remarks1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='BPAddresses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='Notes',
            field=models.TextField(blank=True),
        ),
    ]
