# Generated by Django 3.2.13 on 2023-05-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0014_auto_20230502_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpbranch',
            name='BuildingFloorRoom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bpbranch',
            name='ShipToRemark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bpemployee',
            name='Remarks1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='BPAddresses',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='Notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
