# Generated by Django 3.2.13 on 2023-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('ops_revision', models.CharField(blank=True, max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('ops_number', models.CharField(blank=True, max_length=200)),
                ('amendment', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('open_date', models.CharField(blank=True, max_length=200)),
                ('close_date', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approval_status', models.CharField(blank=True, default='Pending', max_length=200)),
                ('remark', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
