# Generated by Django 3.2.13 on 2023-06-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amendment', '0003_auto_20230609_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amendment',
            name='remark',
        ),
    ]
