# Generated by Django 3.2.13 on 2023-08-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amendment', '0004_remove_amendment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='machine_sp_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
