# Generated by Django 3.2.13 on 2023-03-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DraftOrder', '0002_addondocumentlines_parentitemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftorder',
            name='ConsultingFee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='draftorder',
            name='SolutionType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
