# Generated by Django 3.2.13 on 2023-05-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DraftOrder', '0004_auto_20230309_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressextension',
            name='BillToBuilding',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addressextension',
            name='BillToStreet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addressextension',
            name='ShipToStreet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='ItemDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Special_Remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='draftorder',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='draftorder',
            name='Comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='draftorder',
            name='OtherInstruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='draftorder',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='draftorder',
            name='technical_details',
            field=models.TextField(blank=True),
        ),
    ]
