# Generated by Django 3.2.13 on 2023-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DraftOrder', '0006_auto_20230605_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='customize',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
