# Generated by Django 3.2.7 on 2022-09-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=0, unique=True)),
                ('GroupName', models.CharField(max_length=100)),
            ],
        ),
    ]
