# Generated by Django 3.2.13 on 2022-09-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0002_staticstage_utype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticstage',
            name='UTYPE',
        ),
    ]
