# Generated by Django 3.2.13 on 2022-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0004_staticstage_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='OPStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='SolutionType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
