# Generated by Django 3.2.13 on 2022-11-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0005_auto_20220928_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppitem',
            name='Tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='oppitem',
            name='UomNo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
