# Generated by Django 3.2.13 on 2023-02-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0006_auto_20221103_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppitem',
            name='IT_Intall',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='oppitem',
            name='IT_LOCharges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='oppitem',
            name='IT_MICharges',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
