# Generated by Django 3.2.13 on 2023-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0008_auto_20230309_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='Remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oppitem',
            name='FreeText',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='Remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='StatusRemarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='Comment',
            field=models.TextField(blank=True),
        ),
    ]
