# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0009_auto_20230502_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stageno', models.FloatField(default=1)),
                ('StartDate', models.CharField(blank=True, max_length=100)),
                ('CompletedDate', models.CharField(blank=True, max_length=100)),
                ('Comments', models.TextField(blank=True)),
                ('Opp_Id', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('UpdateDate', models.CharField(blank=True, max_length=60)),
                ('UpdateTime', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PreSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stageno', models.FloatField(default=2)),
                ('StartDate', models.CharField(blank=True, max_length=100)),
                ('CompletedDate', models.CharField(blank=True, max_length=100)),
                ('Shaft', models.CharField(blank=True, max_length=250)),
                ('ShaftWidth', models.CharField(blank=True, max_length=250)),
                ('ShaftDepth', models.CharField(blank=True, max_length=250)),
                ('TotalTravel', models.CharField(blank=True, max_length=250)),
                ('SideWallA', models.CharField(blank=True, max_length=250)),
                ('SideWallC', models.CharField(blank=True, max_length=250)),
                ('PitDepth', models.CharField(blank=True, max_length=250)),
                ('Comments', models.TextField(blank=True)),
                ('Opp_Id', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('UpdateDate', models.CharField(blank=True, max_length=60)),
                ('UpdateTime', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stageno', models.FloatField(default=3)),
                ('StartDate', models.CharField(blank=True, max_length=100)),
                ('CompletedDate', models.CharField(blank=True, max_length=100)),
                ('SupplierCost', models.FloatField(default=0)),
                ('Comments', models.TextField(blank=True)),
                ('Opp_Id', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('UpdateDate', models.CharField(blank=True, max_length=60)),
                ('UpdateTime', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stageno', models.FloatField(default=2)),
                ('StartDate', models.CharField(blank=True, max_length=100)),
                ('CompletedDate', models.CharField(blank=True, max_length=100)),
                ('Shaft', models.CharField(blank=True, max_length=250)),
                ('ShaftWidth', models.CharField(blank=True, max_length=250)),
                ('ShaftDepth', models.CharField(blank=True, max_length=250)),
                ('TotalTravel', models.CharField(blank=True, max_length=250)),
                ('SideWallA', models.CharField(blank=True, max_length=250)),
                ('SideWallC', models.CharField(blank=True, max_length=250)),
                ('PitDepth', models.CharField(blank=True, max_length=250)),
                ('Comments', models.TextField(blank=True)),
                ('Opp_Id', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('UpdateDate', models.CharField(blank=True, max_length=60)),
                ('UpdateTime', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='oppitem',
            name='EndDate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oppitem',
            name='Frequency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='oppitem',
            name='IsService',
            field=models.CharField(default='tNO', max_length=10),
        ),
        migrations.AddField(
            model_name='oppitem',
            name='ReferenceItem',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oppitem',
            name='ReferenceSerial',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oppitem',
            name='StartDate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='CreatedBy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='DepName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='INStatus',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='OppStatus',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='PRStatus',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='RFStatus',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='STStatus',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tender_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
