# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueType', models.CharField(blank=True, max_length=100)),
                ('Description', models.TextField(blank=True, max_length=1000)),
                ('TicketId', models.CharField(blank=True, max_length=20)),
                ('CreatedBy', models.CharField(blank=True, max_length=20)),
                ('CreatedDate', models.CharField(blank=True, max_length=20)),
                ('CreatedTime', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=250)),
                ('IssueCategory', models.CharField(blank=True, max_length=250)),
                ('CreatedBy', models.CharField(blank=True, max_length=150)),
                ('CreatedDate', models.CharField(blank=True, max_length=50)),
                ('CreatedTime', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('CreatedBy', models.CharField(blank=True, max_length=150)),
                ('CreatedDate', models.CharField(blank=True, max_length=50)),
                ('CreatedTime', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
