# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryId', models.CharField(blank=True, max_length=200)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('ListFor', models.IntegerField(default=1)),
                ('LineNo', models.IntegerField(default=0)),
                ('Name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
