# Generated by Django 3.2.13 on 2023-06-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IssueCategory', '0001_initial'),
        ('Issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='IssueCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IssueCategory.issuecategory'),
        ),
    ]
