# Generated by Django 3.2.7 on 2022-09-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('consultant_code', models.CharField(blank=True, max_length=100)),
                ('consultant_name', models.CharField(blank=True, max_length=250)),
                ('expected_start_date', models.CharField(blank=True, max_length=50)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('attach', models.CharField(blank=True, max_length=250)),
                ('cardcode', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.CharField(max_length=50)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('project_owner', models.CharField(blank=True, max_length=50)),
                ('architect', models.CharField(blank=True, max_length=50)),
                ('mep_consultant', models.CharField(blank=True, max_length=50)),
                ('project_cost', models.CharField(blank=True, max_length=50)),
                ('project_status', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
