# Generated by Django 3.2.13 on 2022-09-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20220929_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attach',
        ),
        migrations.RemoveField(
            model_name='project',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='project',
            name='CreatedDate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='CreatedTime',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
