# Generated by Django 3.2.13 on 2022-09-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20220929_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kit_contact_person',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='mep_contact_person',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='pm_contact_person',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
