# Generated by Django 3.2.13 on 2022-10-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20220930_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='GroupType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
