# Generated by Django 3.2.13 on 2022-11-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20221011_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cardcode',
            new_name='CardCode',
        ),
    ]
