# Generated by Django 3.2.7 on 2022-09-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=0, unique=True)),
                ('GroupName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(blank=True, max_length=100)),
                ('clientEmail', models.CharField(blank=True, max_length=70)),
                ('clientMobile', models.CharField(blank=True, max_length=20)),
                ('clientAddress', models.TextField(blank=True)),
                ('clientGST', models.CharField(blank=True, max_length=30)),
                ('bankName', models.CharField(blank=True, max_length=40)),
                ('bankIFSC', models.CharField(blank=True, max_length=40)),
                ('bankAccountNo', models.CharField(blank=True, max_length=100)),
                ('AccountHolderName', models.CharField(blank=True, max_length=100)),
                ('TermsConditions', models.TextField(blank=True)),
            ],
        ),
    ]
