# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientBankDetails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
