# Generated by Django 3.2.7 on 2022-09-05 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=250)),
                ('Lead_Id', models.CharField(blank=True, max_length=10)),
                ('Emp_Id', models.CharField(blank=True, max_length=10)),
                ('Emp_Name', models.CharField(blank=True, max_length=50)),
                ('UpdateDate', models.CharField(blank=True, max_length=100)),
                ('UpdateTime', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineNum', models.IntegerField(default=0)),
                ('LeadID', models.CharField(blank=True, max_length=5)),
                ('Quantity', models.IntegerField(default=0)),
                ('UnitPrice', models.FloatField(default=0)),
                ('DiscountPercent', models.FloatField(default=0)),
                ('ItemCode', models.CharField(blank=True, max_length=20)),
                ('ItemDescription', models.CharField(blank=True, max_length=150)),
                ('TaxCode', models.CharField(blank=True, max_length=10)),
                ('U_FGITEM', models.CharField(blank=True, max_length=20)),
                ('CostingCode2', models.CharField(blank=True, max_length=20)),
                ('ProjectCode', models.CharField(blank=True, max_length=20)),
                ('FreeText', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('CreatedDate', models.CharField(blank=True, max_length=50)),
                ('CreatedTime', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('CreatedDate', models.CharField(blank=True, max_length=50)),
                ('CreatedTime', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('companyName', models.CharField(blank=True, max_length=100)),
                ('numOfEmployee', models.IntegerField(default='0')),
                ('turnover', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=10)),
                ('contactPerson', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=20)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('leadType', models.CharField(blank=True, max_length=50)),
                ('productInterest', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('tender', models.IntegerField(default='0')),
                ('category', models.CharField(blank=True, max_length=250)),
                ('groupType', models.CharField(blank=True, max_length=250)),
                ('intProdCat', models.CharField(blank=True, max_length=250)),
                ('intProjCat', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, max_length=250)),
                ('country_code', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('state_code', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('DivCode', models.CharField(blank=True, max_length=50)),
                ('DivName', models.CharField(blank=True, max_length=50)),
                ('BPStatus', models.CharField(blank=True, max_length=2)),
                ('OPStatus', models.CharField(blank=True, max_length=2)),
                ('TDStatus', models.CharField(blank=True, max_length=2)),
                ('QTStatus', models.CharField(blank=True, max_length=2)),
                ('ODStatus', models.CharField(blank=True, max_length=2)),
                ('junk', models.IntegerField(default='0')),
                ('timestamp', models.CharField(blank=True, max_length=60)),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedTo', to='Employee.employee')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
