# Generated by Django 3.2.13 on 2022-09-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='code',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
