# Generated by Django 4.2.2 on 2023-09-19 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerId', models.CharField(blank=True, max_length=10)),
                ('OwnerType', models.CharField(blank=True, default='Employee', max_length=20)),
                ('BillToAddress', models.CharField(blank=True, max_length=255)),
                ('EstimateAmt', models.CharField(blank=True, max_length=100)),
                ('WarrantyStatus', models.CharField(blank=True, default='Warranty Expired', max_length=100)),
                ('WarrantyDate', models.CharField(blank=True, default='', max_length=100)),
                ('ApproverId', models.CharField(blank=True, max_length=10)),
                ('RequestedDate', models.CharField(blank=True, max_length=20)),
                ('ApprovedDate', models.CharField(blank=True, max_length=20)),
                ('Status', models.CharField(blank=True, default='Pending', max_length=100)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Priority', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('SourceType', models.CharField(blank=True, max_length=100)),
                ('SourceID', models.CharField(blank=True, max_length=5)),
                ('Read', models.CharField(blank=True, max_length=5)),
                ('SalesEmployeeCode', models.CharField(blank=True, max_length=5)),
                ('CreatedDateTime', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('SubType', models.CharField(blank=True, max_length=100)),
                ('Stageno', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TicketChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=250)),
                ('Description', models.TextField(blank=True)),
                ('Comment', models.TextField(blank=True)),
                ('Data', models.TextField(blank=True)),
                ('Field1', models.CharField(blank=True, max_length=250)),
                ('Field2', models.CharField(blank=True, max_length=250)),
                ('Field3', models.CharField(blank=True, max_length=250)),
                ('Field4', models.CharField(blank=True, max_length=250)),
                ('Field5', models.CharField(blank=True, max_length=250)),
                ('Status', models.IntegerField(blank=True, default=0)),
                ('Duration', models.CharField(blank=True, max_length=100)),
                ('TicketId', models.CharField(blank=True, max_length=100)),
                ('CreatedDate', models.CharField(blank=True, max_length=100)),
                ('CreatedTime', models.CharField(blank=True, max_length=100)),
                ('UpdatedDate', models.CharField(blank=True, max_length=100)),
                ('UpdatedTime', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryID', models.CharField(blank=True, max_length=100)),
                ('Stageno', models.CharField(blank=True, max_length=10)),
                ('AssignTo', models.CharField(blank=True, max_length=10)),
                ('CreatedBy', models.CharField(blank=True, max_length=10)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('TypeChange', models.CharField(default='NO', max_length=100)),
                ('SubType', models.CharField(blank=True, max_length=100)),
                ('Title', models.CharField(blank=True, max_length=250)),
                ('BpCardCode', models.CharField(blank=True, max_length=100)),
                ('BpBranch', models.CharField(blank=True, max_length=100)),
                ('ContactName', models.CharField(blank=True, max_length=250)),
                ('ContactPhone', models.CharField(blank=True, max_length=100)),
                ('CountryCode', models.CharField(blank=True, max_length=100)),
                ('AlternatePhone', models.CharField(blank=True, max_length=100)),
                ('CountryCode1', models.CharField(blank=True, max_length=100)),
                ('ContactEmail', models.CharField(blank=True, max_length=250)),
                ('ContactAddress', models.TextField(blank=True)),
                ('ProductSerialNo', models.CharField(blank=True, max_length=250)),
                ('ProductName', models.CharField(blank=True, max_length=250)),
                ('ProductCategory', models.CharField(blank=True, max_length=250)),
                ('ProductModelNo', models.CharField(blank=True, max_length=250)),
                ('Zone', models.CharField(blank=True, max_length=100)),
                ('Priority', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('Description', models.TextField(blank=True)),
                ('Observation', models.TextField(blank=True)),
                ('DurationOfService', models.CharField(blank=True, default='0:0', max_length=100)),
                ('SignatureStatus', models.CharField(blank=True, default='Pending', max_length=100)),
                ('WarrantyStartDate', models.CharField(blank=True, default='', max_length=50)),
                ('WarrantyDueDate', models.CharField(blank=True, default='', max_length=50)),
                ('ExtWarrantyStartDate', models.CharField(blank=True, default='', max_length=50)),
                ('ExtWarrantyDueDate', models.CharField(blank=True, default='', max_length=50)),
                ('AMCStartDate', models.CharField(blank=True, default='', max_length=50)),
                ('AMCDueDate', models.CharField(blank=True, default='', max_length=50)),
                ('CMCStartDate', models.CharField(blank=True, default='', max_length=50)),
                ('CMCDueDate', models.CharField(blank=True, default='', max_length=50)),
                ('ContractType', models.CharField(blank=True, default='', max_length=50)),
                ('ManufacturingDate', models.CharField(blank=True, default='', max_length=50)),
                ('ExpiryDate', models.CharField(blank=True, default='', max_length=50)),
                ('CreateDate', models.DateField(auto_now_add=True)),
                ('ClosedDate', models.CharField(blank=True, max_length=50)),
                ('DueDate', models.CharField(blank=True, default='', max_length=50)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDatetime', models.DateTimeField(auto_now_add=True)),
                ('TicketStatus', models.CharField(blank=True, default='Pending', max_length=50)),
                ('PartRequest', models.IntegerField(default=0)),
                ('TicketStartDate', models.CharField(blank=True, default='', max_length=50)),
                ('TicketEndDate', models.CharField(blank=True, default='', max_length=50)),
                ('SysScheduleDate', models.CharField(blank=True, max_length=50)),
                ('AppScheduleDate', models.CharField(blank=True, max_length=50)),
                ('AcceptedAt', models.CharField(blank=True, max_length=50)),
                ('RescueAt', models.CharField(blank=True, max_length=50)),
                ('Data', models.TextField(blank=True, default='')),
                ('CustomerPIR', models.CharField(blank=True, default='', max_length=250)),
                ('SignatureFile', models.CharField(blank=True, default='', max_length=250)),
                ('CustomerFeedback', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketStatus', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('Stageno', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zone', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(blank=True, max_length=255)),
                ('Comment', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(default='False', max_length=100)),
                ('Duration', models.CharField(blank=True, max_length=100)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('TicketId', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Tickets.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='RescueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('Remarks', models.CharField(blank=True, max_length=250)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('TicketId', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Tickets.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='PRStatusRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalesEmployeeCode', models.CharField(blank=True, max_length=10)),
                ('Status', models.CharField(blank=True, max_length=50)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('PRID', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Tickets.partrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PRItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCode', models.CharField(blank=True, max_length=100)),
                ('ItemQty', models.CharField(blank=True, max_length=100)),
                ('UnitPrice', models.CharField(blank=True, max_length=100)),
                ('Discount', models.CharField(blank=True, max_length=100)),
                ('Comments', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(blank=True, default='Pending', max_length=100)),
                ('ProjectCode', models.CharField(blank=True, max_length=100)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('PRID', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Tickets.partrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PRAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attachment', models.CharField(blank=True, max_length=100)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('PRID', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Tickets.partrequest')),
            ],
        ),
        migrations.AddField(
            model_name='partrequest',
            name='TicketId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Tickets.tickets'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrevType', models.CharField(blank=True, max_length=100)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('Remarks', models.CharField(blank=True, max_length=100)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('TicketId', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Tickets.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerId', models.CharField(blank=True, max_length=10)),
                ('OwnerType', models.CharField(blank=True, max_length=100)),
                ('Message', models.CharField(blank=True, max_length=255)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('TicketId', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Tickets.tickets')),
            ],
        ),
    ]
