# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
