# Generated by Django 3.2.13 on 2023-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='IT_Intall',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='IT_LOCharges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='IT_MICharges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='CivilWorkCharges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='IncidentalCharges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='PlumbingCharges',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
