from django.db import models  

class Delivery(models.Model):
    TaxDate = models.CharField(max_length=30, blank=True)
    DocDueDate = models.CharField(max_length=30, blank=True)
    ContactPersonCode = models.CharField(max_length=5, blank=True)
    DiscountPercent = models.FloatField(default=0)
    DocDate = models.CharField(max_length=30, blank=True)
    CardCode = models.CharField(max_length=50, blank=True)
    Comments = models.CharField(max_length=250, blank=True)
    SalesPersonCode = models.CharField(max_length=5, blank=True)
    
    DocumentStatus = models.CharField(max_length=50, blank=True)
    DocCurrency = models.CharField(max_length=50, blank=True)
    DocTotal = models.CharField(max_length=50, blank=True)
    CardName = models.CharField(max_length=150, blank=True)
    VatSum = models.CharField(max_length=50, blank=True)
    CreationDate = models.CharField(max_length=50, blank=True)
    
    DocEntry         = models.CharField(max_length=10, blank=True)
    OrderId          = models.CharField(max_length=10, blank=True)
    PaymentGroupCode = models.CharField(max_length=10, blank=True)
    U_Term_Condition = models.TextField(blank=True)
    
    BPLID = models.CharField(max_length=5, blank=True)
    
    CreateDate = models.CharField(max_length=30, blank=True)
    CreateTime = models.CharField(max_length=30, blank=True)
    UpdateDate = models.CharField(max_length=30, blank=True)
    UpdateTime = models.CharField(max_length=30, blank=True)
    ShippingAndHandling = models.CharField(max_length=10, blank=True, default="0")

class AddressExtension(models.Model):
    DeliveryId = models.CharField(max_length=5, blank=True)
    BillToBuilding = models.CharField(max_length=100, blank=True)
    ShipToState = models.CharField(max_length=100, blank=True)
    BillToCity = models.CharField(max_length=100, blank=True)
    ShipToCountry = models.CharField(max_length=100, blank=True)
    BillToZipCode = models.CharField(max_length=100, blank=True)
    ShipToStreet = models.CharField(max_length=100, blank=True)
    BillToState = models.CharField(max_length=100, blank=True)
    ShipToZipCode = models.CharField(max_length=100, blank=True)
    BillToStreet = models.CharField(max_length=100, blank=True)
    ShipToBuilding = models.CharField(max_length=250, blank=True)
    ShipToCity = models.CharField(max_length=100, blank=True)
    BillToCountry = models.CharField(max_length=100, blank=True)
    U_SCOUNTRY = models.CharField(max_length=100, blank=True)
    U_SSTATE = models.CharField(max_length=100, blank=True)
    U_SHPTYPB = models.CharField(max_length=100, blank=True)
    U_BSTATE = models.CharField(max_length=100, blank=True)
    U_BCOUNTRY = models.CharField(max_length=100, blank=True)
    U_SHPTYPS = models.CharField(max_length=100, blank=True)


class DocumentLines(models.Model):
    LineNum          = models.IntegerField(default=0)
    DeliveryId       = models.CharField(max_length=10, blank=True)
    OrderId          = models.CharField(max_length=10, blank=True)
    BaseEntry        = models.CharField(max_length=10, blank=True)
    DeliveryChallanNumber = models.CharField(max_length=10, blank=True)
    Quantity         = models.IntegerField(default=0)
    UnitPrice        = models.FloatField(default=0)
    DiscountPercent  = models.FloatField(default=0)

    TaxCode          = models.CharField(max_length=100, blank=True)
    BarCode          = models.CharField(max_length=100, default="")
    SerialNo         = models.CharField(max_length=100, default="")
    ItemCode         = models.CharField(max_length=100, blank=True)
    ItemName         = models.CharField(max_length=150, blank=True)
    ItemCategory     = models.CharField(max_length=150, blank=True)
    ItemDescription  = models.CharField(max_length=150, blank=True)
    U_FGITEM         = models.CharField(max_length=100, blank=True)
    CostingCode2     = models.CharField(max_length=100, blank=True)
    ProjectCode      = models.CharField(max_length=100, blank=True)
    FreeText         = models.CharField(max_length=500, blank=True)

    EstimatedDeliveryDate= models.CharField(max_length=50, default="")
    WarrantyType         = models.CharField(max_length=50, default="")
    WarrantyStartDate    = models.CharField(max_length=50, default="")
    WarrantyDueDate      = models.CharField(max_length=50, default="")
    ExtWarrantyStartDate = models.CharField(max_length=50, default="")
    ExtWarrantyDueDate   = models.CharField(max_length=50, default="")
    AMCStartDate         = models.CharField(max_length=50, default="")
    AMCDueDate           = models.CharField(max_length=50, default="")
    CMCStartDate         = models.CharField(max_length=50, default="")
    CMCDueDate           = models.CharField(max_length=50, default="")
    ManufacturingDate    = models.CharField(max_length=50, default="")
    ExpiryDate           = models.CharField(max_length=50, default="")
    Status               = models.CharField(max_length=50, default="") # Available, Unavailable, Allocated
    TaxRate              = models.CharField(max_length=10, blank=True,default=0)


class DeliveryAttachments(models.Model):
    DeliveryId      = models.CharField(max_length=5, blank=True)
    File            = models.CharField(max_length=255, blank=True)
    Datetime        = models.DateTimeField(auto_now_add=True)