# Generated by Django 3.2.13 on 2022-11-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20221011_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='At_Capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Ct_Capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Ht_Capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Machine_Body_Material',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Machine_Colour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Machine_Dimension',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Pro_Capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Sales_Type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Special_Remark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Tap_Qty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Tap_Type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='Type_of_Machine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='UV_Germ',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
