# Generated by Django 3.2.13 on 2022-11-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20221101_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='Tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='documentlines',
            name='UomNo',
            field=models.FloatField(default=0),
        ),
    ]
