# Generated by Django 3.2.13 on 2022-11-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_auto_20221102_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlines',
            name='UomNo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
