# Generated by Django 3.2.13 on 2022-11-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_alter_documentlines_uomno'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addendum',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='approved_drawing',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='technical_details',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
