# Generated by Django 3.2.13 on 2022-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_auto_20221104_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_prefix', models.CharField(blank=True, max_length=100)),
                ('counter', models.IntegerField(default=0)),
                ('OrderId', models.IntegerField(default=0)),
                ('CustCodeBp', models.CharField(max_length=100)),
            ],
        ),
    ]
