# Generated by Django 3.2.13 on 2022-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_custcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='urn_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
