# Generated by Django 3.2.13 on 2022-11-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_rename_urn_no_order_urn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='NetTotal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
