# Generated by Django 3.2.13 on 2023-02-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_auto_20230220_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CardCodeEnd',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='CardNameEnd',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='ContactPersonCodeEnd',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
