# Generated by Django 3.2.13 on 2023-02-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Order', '0017_auto_20230220_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSlave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Min', models.FloatField(default=0)),
                ('Max', models.FloatField(default=0)),
                ('Level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='FinalStatus',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='OrdLevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrdLevel1', to='Employee.employee', to_field='SalesEmployeeCode'),
        ),
        migrations.AddField(
            model_name='order',
            name='OrdLevel1Status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='OrdLevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrdLevel2', to='Employee.employee', to_field='SalesEmployeeCode'),
        ),
        migrations.AddField(
            model_name='order',
            name='OrdLevel2Status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='OrdLevel3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrdLevel3', to='Employee.employee', to_field='SalesEmployeeCode'),
        ),
        migrations.AddField(
            model_name='order',
            name='OrdLevel3Status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
