# Generated by Django 3.2.13 on 2023-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_auto_20230221_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CivilWorkSide',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='CrainCharges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='LabourCharges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='PlumbingStatusSide',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='SiteSurveySide',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
