# Generated by Django 3.2.13 on 2023-02-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_auto_20230222_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedDate', models.CharField(blank=True, max_length=30)),
                ('CreatedTime', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
