# Generated by Django 3.2.13 on 2023-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0021_machinetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='SiteSurveySerialNo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
