# Generated by Django 3.2.13 on 2023-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0022_order_sitesurveyserialno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnDocumentLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineNum', models.IntegerField(default=0)),
                ('OrderID', models.CharField(blank=True, max_length=5)),
                ('Quantity', models.IntegerField(default=0)),
                ('UnitPrice', models.FloatField(default=0)),
                ('ItemDescription', models.CharField(blank=True, max_length=150)),
                ('ItemCode', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='AddOn',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
