# Generated by Django 3.2.13 on 2023-02-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0023_auto_20230227_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='AddOn',
        ),
    ]
