# Generated by Django 3.2.13 on 2023-03-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0027_auto_20230309_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ReadLevel1',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='ReadLevel2',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
