# Generated by Django 3.2.13 on 2023-03-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0028_auto_20230314_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ReadLevel3',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
