# Generated by Django 3.2.13 on 2023-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0031_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addondocumentlines',
            name='ItemDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='ItemDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Special_Remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='technical_details',
            field=models.TextField(blank=True),
        ),
    ]
