# Generated by Django 3.2.13 on 2023-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0032_auto_20230502_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressextension',
            name='BillToBuilding',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='OtherInstruction',
            field=models.TextField(blank=True),
        ),
    ]
