# Generated by Django 3.2.13 on 2023-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0033_auto_20230503_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PoNo',
            field=models.TextField(blank=True),
        ),
    ]
