# Generated by Django 3.2.13 on 2023-06-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0034_alter_order_pono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlines',
            name='At_Capacity',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='CostingCode2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Ct_Capacity',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='FreeText',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Ht_Capacity',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='IT_Intall',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='IT_LOCharges',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='IT_MICharges',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='ItemCode',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='ItemDescription',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Machine_Body_Material',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Machine_Colour',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Machine_Dimension',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Pro_Capacity',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='ProjectCode',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Sales_Type',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Tap_Qty',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Tap_Type',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='TaxCode',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='Type_of_Machine',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='UV_Germ',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='U_FGITEM',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentlines',
            name='UomNo',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
