# Generated by Django 3.2.13 on 2023-06-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0035_auto_20230605_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amendment_action',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='amendment_status',
            field=models.CharField(blank=True, default='Inactive', max_length=200),
        ),
    ]
