# Generated by Django 3.2.13 on 2023-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0036_auto_20230607_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(blank=True, max_length=5)),
                ('SalesEmployeeCode', models.CharField(blank=True, max_length=5)),
                ('Status', models.CharField(blank=True, max_length=50)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
