# Generated by Django 3.2.13 on 2023-06-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0038_delete_orderstatusremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(blank=True, default=0)),
                ('OrderID', models.CharField(blank=True, max_length=200)),
                ('DocTotal', models.CharField(blank=True, max_length=50)),
                ('NetTotal', models.CharField(blank=True, max_length=50)),
                ('CreatedDate', models.CharField(blank=True, max_length=30)),
                ('CreatedTime', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLinesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineNum', models.IntegerField(default=0)),
                ('OrderID', models.CharField(blank=True, max_length=5)),
                ('Quantity', models.IntegerField(default=0)),
                ('UnitPrice', models.FloatField(default=0)),
                ('DiscountPercent', models.FloatField(default=0)),
                ('ItemDescription', models.TextField(blank=True, max_length=1000)),
                ('ItemCode', models.TextField(blank=True, max_length=1000)),
                ('TaxCode', models.TextField(blank=True, max_length=1000)),
                ('U_FGITEM', models.TextField(blank=True, max_length=1000)),
                ('CostingCode2', models.TextField(blank=True, max_length=1000)),
                ('ProjectCode', models.TextField(blank=True, max_length=1000)),
                ('FreeText', models.TextField(blank=True, max_length=1000)),
                ('Tap_Qty', models.TextField(blank=True, max_length=1000)),
                ('Tap_Type', models.TextField(blank=True, max_length=1000)),
                ('Ht_Capacity', models.TextField(blank=True, max_length=1000)),
                ('Ct_Capacity', models.TextField(blank=True, max_length=1000)),
                ('At_Capacity', models.TextField(blank=True, max_length=1000)),
                ('Pro_Capacity', models.TextField(blank=True, max_length=1000)),
                ('Machine_Dimension', models.TextField(blank=True, max_length=1000)),
                ('Machine_Colour', models.TextField(blank=True, max_length=1000)),
                ('Type_of_Machine', models.TextField(blank=True, max_length=1000)),
                ('Machine_Body_Material', models.TextField(blank=True, max_length=1000)),
                ('UV_Germ', models.TextField(blank=True, max_length=1000)),
                ('Sales_Type', models.TextField(blank=True, max_length=1000)),
                ('Special_Remark', models.TextField(blank=True)),
                ('IT_MICharges', models.TextField(blank=True, max_length=1000)),
                ('IT_LOCharges', models.TextField(blank=True, max_length=1000)),
                ('IT_Intall', models.TextField(blank=True, max_length=1000)),
                ('Tax', models.FloatField(default=0)),
                ('UomNo', models.TextField(blank=True, max_length=1000)),
                ('orderhistory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.orderhistory')),
            ],
        ),
        migrations.CreateModel(
            name='AddOnDocumentLinesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineNum', models.IntegerField(default=0)),
                ('OrderID', models.CharField(blank=True, max_length=5)),
                ('Quantity', models.IntegerField(default=0)),
                ('UnitPrice', models.FloatField(default=0)),
                ('ItemDescription', models.TextField(blank=True)),
                ('ItemCode', models.CharField(blank=True, max_length=20)),
                ('ParentItemCode', models.CharField(blank=True, max_length=20)),
                ('documentlineshistory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.documentlineshistory')),
            ],
        ),
    ]
