# Generated by Django 4.2.2 on 2023-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0040_documentlines_customize'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AMCOrdId', models.CharField(blank=True, max_length=5)),
                ('OrderID', models.CharField(blank=True, max_length=5)),
                ('LineNum', models.CharField(blank=True, max_length=5)),
                ('ItemCode', models.CharField(blank=True, max_length=50)),
                ('ItemName', models.CharField(blank=True, max_length=255)),
                ('FromDate', models.CharField(blank=True, max_length=50)),
                ('Todate', models.CharField(blank=True, max_length=50)),
                ('UnitPrice', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AMCSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(blank=True, max_length=5)),
                ('LineNum', models.CharField(blank=True, max_length=50)),
                ('CardCode', models.CharField(blank=True, max_length=100)),
                ('ItemCode', models.CharField(blank=True, max_length=50)),
                ('ItemName', models.CharField(blank=True, max_length=255)),
                ('ItemSerialNo', models.CharField(blank=True, max_length=100)),
                ('Frequency', models.CharField(blank=True, max_length=50)),
                ('DocEntry', models.CharField(blank=True, max_length=50)),
                ('EXWRSTDT', models.CharField(blank=True, max_length=50)),
                ('EXWREDDT', models.CharField(blank=True, max_length=50)),
                ('EXWRAMT', models.CharField(blank=True, max_length=50)),
                ('ContractStatus', models.CharField(blank=True, default='false', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(blank=True, max_length=50)),
                ('Name', models.CharField(max_length=150)),
                ('Stageno', models.FloatField(default=0)),
                ('PaymentPercentage', models.FloatField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('Comment', models.CharField(blank=True, max_length=500)),
                ('File', models.CharField(blank=True, max_length=250)),
                ('CreateDate', models.CharField(blank=True, max_length=100)),
                ('CreateTime', models.CharField(blank=True, max_length=100)),
                ('UpdateDate', models.CharField(blank=True, max_length=100)),
                ('UpdateTime', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStaticstage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('DepName', models.CharField(default='New Product', max_length=150)),
                ('Stageno', models.FloatField(default=0)),
                ('PaymentPercentage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(blank=True, max_length=5)),
                ('SalesEmployeeCode', models.CharField(blank=True, max_length=5)),
                ('Status', models.CharField(blank=True, max_length=50)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(blank=True, max_length=10)),
                ('DocEntry', models.CharField(blank=True, max_length=50)),
                ('AMCSalesOrderId', models.CharField(blank=True, max_length=10)),
                ('CardCode', models.CharField(blank=True, max_length=100)),
                ('BPName', models.CharField(blank=True, max_length=200)),
                ('ContractType', models.CharField(blank=True, max_length=100)),
                ('BillAddrId', models.CharField(blank=True, max_length=100)),
                ('BillAddr', models.CharField(blank=True, max_length=250)),
                ('ShipAddrId', models.CharField(blank=True, max_length=100)),
                ('ShipAddr', models.CharField(blank=True, max_length=250)),
                ('U_STATUS', models.CharField(blank=True, max_length=100)),
                ('U_CONTACTPER', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContractsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceContractsId', models.CharField(blank=True, max_length=10)),
                ('LineId', models.CharField(blank=True, max_length=10)),
                ('DocEntry', models.CharField(blank=True, max_length=50)),
                ('Frequency', models.CharField(blank=True, max_length=10)),
                ('ItemCode', models.CharField(blank=True, max_length=250)),
                ('ItemName', models.CharField(blank=True, max_length=250)),
                ('AMCItemCode', models.CharField(blank=True, max_length=250)),
                ('AMCItemName', models.CharField(blank=True, max_length=250)),
                ('ItemSerialNo', models.CharField(blank=True, max_length=250)),
                ('FromDate', models.CharField(blank=True, max_length=30)),
                ('Todate', models.CharField(blank=True, max_length=30)),
                ('ItemAMT', models.CharField(blank=True, max_length=10)),
                ('TicketGen', models.CharField(blank=True, default='False', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='CreatedBy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='DepName',
            field=models.CharField(blank=True, default='New Product', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='PRID',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='PoAmt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='ShippingAndHandling',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='TermsAndConditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='U_Pay1',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='U_Pay2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='U_Pay3',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='U_Pay4',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='U_Pay5',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
