# Generated by Django 4.2.2 on 2023-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0041_amcorderitem_amcsalesorder_orderstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='Comments',
            field=models.TextField(blank=True),
        ),
    ]
